Lab7_Identity/Lab7_Identity/Controllers/FITController.cs
using Lab7_Identity.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7_Identity.Controllers
{
    [AuthAction]
    public class FITController : Controller
    {
        // GET: FIT
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIT_IS()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIT_PI()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIT_ID()
        {
            return View();
        }
    }
}

Lab7_Identity/Lab7_Identity/Views/FIT/FIT_ID.cshtml
@{
    ViewBag.Title = "FIT_ID";
}

<h2>FIT_ID</h2>

@Html.ActionLink("FIT Index", "Index", "FIT")

Lab7_Identity/Lab7_Identity/Views/FIT/FIT_IS.cshtml
@{
    ViewBag.Title = "FIT_IS";
}

<h2>FIT_IS</h2>

@Html.ActionLink("FIT Index", "Index", "FIT")

Lab7_Identity/Lab7_Identity/Views/FIT/FIT_PI.cshtml
@{
    ViewBag.Title = "FIT_PI";
}

<h2>FIT_PI</h2>

@Html.ActionLink("FIT Index", "Index", "FIT")

Lab7_Identity/Lab7_Identity/Views/FIT/Index.cshtml
@{
    ViewBag.Title = "FIT Index";
}

<h2>FIT Index</h2>

@Html.ActionLink("FIT_IS", "FIT_IS", "FIT")
@Html.ActionLink("FIT_PI", "FIT_PI", "FIT")
@Html.ActionLink("FIT_ID", "FIT_ID", "FIT")