Lab7_Identity/Lab7_Identity/Controllers/FLTController.cs
using Lab7_Identity.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7_Identity.Controllers
{
    [AuthAction]
    public class FLTController : Controller
    {
        // GET: FLT
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FLT_LV()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIT_LU()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIT_LZ()
        {
            return View();
        }
    }
}

Lab7_Identity/Lab7_Identity/Views/FLT/FIT_LU.cshtml
@{
    ViewBag.Title = "FIT_LU";
}

<h2>FIT_LU</h2>

@Html.ActionLink("FLT Index", "Index", "FLT")

Lab7_Identity/Lab7_Identity/Views/FLT/FIT_LZ.cshtml
@{
    ViewBag.Title = "FIT_LZ";
}

<h2>FIT_LZ</h2>

@Html.ActionLink("FLT Index", "Index", "FLT")

Lab7_Identity/Lab7_Identity/Views/FLT/FLT_LV.cshtml
@{
    ViewBag.Title = "FLT_LV";
}

<h2>FLT_LV</h2>

@Html.ActionLink("FLT Index", "Index", "FLT")

Lab7_Identity/Lab7_Identity/Views/FLT/Index.cshtml
@{
    ViewBag.Title = "FLT Index";
}

<h2>FLT Index</h2>

@Html.ActionLink("FLT_LV", "FLT_LV", "FLT")
@Html.ActionLink("FIT_LU", "FIT_LU", "FLT")
@Html.ActionLink("FIT_LZ", "FIT_LZ", "FLT")