Lab7_Identity/Lab7_Identity/Controllers/FIEController.cs
using Lab7_Identity.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab7_Identity.Controllers
{
    [AuthAction]
    public class FIEController : Controller
    {
        // GET: FIE
        [Authorize(Roles = "Guest,Employer")]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIE_TM()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UR()
        {
            return View();
        }

        [HttpGet]
        [Authorize(Roles = "Employer")]
        public ActionResult FIE_UP()
        {
            return View();
        }
    }
}

Lab7_Identity/Lab7_Identity/Views/FIE/FIE_TM.cshtml
@{
    ViewBag.Title = "FIE_TM";
}

<h2>FIE_TM</h2>

@Html.ActionLink("FIE Index", "Index", "FIE")

Lab7_Identity/Lab7_Identity/Views/FIE/FIE_UP.cshtml
@{
    ViewBag.Title = "FIE_UP";
}

<h2>FIE_UP</h2>

@Html.ActionLink("FIE Index", "Index", "FIE")

Lab7_Identity/Lab7_Identity/Views/FIE/FIE_UR.cshtml
@{
    ViewBag.Title = "FIE_UR";
}

<h2>FIE_UR</h2>

@Html.ActionLink("FIE Index", "Index", "FIE")

Lab7_Identity/Lab7_Identity/Views/FIE/Index.cshtml
@{
    ViewBag.Title = "FIE Index";
}

<h2>FIE Index</h2>

@Html.ActionLink("FIE_TM", "FIE_TM", "FIE")
@Html.ActionLink("FIE_UR", "FIE_UR", "FIE")
@Html.ActionLink("FIE_UP", "FIE_UP", "FIE")